# https://goreleaser.com
project_name: helloworld
before:
  # https://goreleaser.com/customization/hooks/
  hooks:
    # tidy up and lint
    - go mod tidy
    - go fmt ./...
builds:
  # https://goreleaser.com/customization/build/
  - main: ./helloworld
    binary: helloworld
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
dockers:
  # https://goreleaser.com/customization/docker/
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "0hlov3s/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "0hlov3s/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "0hlov3s/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "0hlov3s/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    image_templates:
      - "0hlov3s/{{ .ProjectName }}:{{ .Version }}-armv6"
      - "0hlov3s/{{ .ProjectName }}:latest-armv6"
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    image_templates:
      - "0hlov3s/{{ .ProjectName }}:{{ .Version }}-armv7"
      - "0hlov3s/{{ .ProjectName }}:latest-armv7"
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: 0hlov3s/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - 0hlov3s/{{ .ProjectName }}:{{ .Version }}-amd64
      - 0hlov3s/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - 0hlov3s/{{ .ProjectName }}:{{ .Version }}-armv6
      - 0hlov3s/{{ .ProjectName }}:{{ .Version }}-armv7
  - name_template: 0hlov3s/{{ .ProjectName }}:latest
    image_templates:
      - 0hlov3s/{{ .ProjectName }}:latest-amd64
      - 0hlov3s/{{ .ProjectName }}:latest-arm64v8
      - 0hlov3s/{{ .ProjectName }}:latest-armv6
      - 0hlov3s/{{ .ProjectName }}:latest-armv7
archives:
  # https://goreleaser.com/customization/archive/
  - files:
      # Standard Release Files
      - LICENSE
      - README.md
checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: 'checksums.txt'
snapshot:
  # https://goreleaser.com/customization/snapshots/
  name_template: "{{ incpatch .Version }}-SNAPSHOT"
source:
  # https://goreleaser.com/customization/source/
  enabled: true
